/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Timer_1.h>
#include <B_press.h>
#include <B_press_aliases.h>
#include <SW2.h>
#include <SW2_aliases.h>
#include <sw_int.h>
#include <V_in.h>
#include <V_in_aliases.h>
#include <ADC.h>
#include <cl_deb.h>
#include <UART_1.h>
#include <UART_1_SPI_UART.h>
#include <UART_1_PINS.h>
#include <UART_1_SPI_UART_PVT.h>
#include <UART_1_PVT.h>
#include <UART_1_BOOT.h>
#include <A0.h>
#include <A0_aliases.h>
#include <LCD.h>
#include <RS.h>
#include <RS_aliases.h>
#include <E.h>
#include <E_aliases.h>
#include <D4.h>
#include <D4_aliases.h>
#include <D5.h>
#include <D5_aliases.h>
#include <D6.h>
#include <D6_aliases.h>
#include <D7.h>
#include <D7_aliases.h>
#include <ADC_IRQ.h>
#include <ADC_intClock.h>
#include <UART_1_SCBCLK.h>
#include <UART_1_tx.h>
#include <UART_1_tx_aliases.h>
#include <LCD_Cntl_Port.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

