# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Snufkin\Documents\PSoC Creator\CRT_timer\CRT_timer.cydsn\CRT_timer.cyprj
# Date: Tue, 10 Mar 2015 23:13:16 GMT
#set_units -time ns
create_clock -name {ADC_1_intClock(FFB)} -period 375 -waveform {0 187.5} [list [get_pins {ClockBlock/ff_div_7}]]
create_clock -name {UART_1_SCBCLK(FFB)} -period 8666.6666666666661 -waveform {0 4333.33333333333} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_generated_clock -name {ADC_1_intClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 9 19} [list]
create_generated_clock -name {cl_deb} -source [get_pins {ClockBlock/hfclk}] -edges {1 2400001 4800001} [list [get_pins {ClockBlock/udb_div_0}]]
create_generated_clock -name {UART_1_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 209 417} -nominal_period 8666.6666666666661 [list]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]


# Component constraints for C:\Users\Snufkin\Documents\PSoC Creator\CRT_timer\CRT_timer.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Snufkin\Documents\PSoC Creator\CRT_timer\CRT_timer.cydsn\CRT_timer.cyprj
# Date: Tue, 10 Mar 2015 23:13:12 GMT
